my_list/urls.py
from django.urls import path

from my_list.views import (
    TaskListView,
    TaskUpdateView,
    TaskCreateView,
    TaskDeleteView,
    TagListView,
    TagUpdateView,
    TagCreateView,
    TagDeleteView,
    ToggleView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("<int:pk>/toggle-is_done/", ToggleView.as_view(), name="toggle-is-done"),
]

app_name = "my_list"

to_do_list/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("my_list.urls", namespace="my_list")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField(max_length=500)
    date_time = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return self.content

my_list/forms.py
from django import forms

from my_list.models import Task, Tag


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"

my_list/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic, View

from my_list.forms import TaskForm, TagForm
from my_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task

    def get_queryset(self):
        return Task.objects.order_by("is_done", "date_time")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("my_list:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("my_list:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("my_list:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("my_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("my_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("my_list:tag-list")


class ToggleView(View):
    @staticmethod
    def post(request, pk, *args, **kwargs):
        task = Task.objects.get(id=pk)
        task.is_done = not task.is_done
        task.save()
        return HttpResponseRedirect(reverse_lazy("my_list:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>To Do List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}


        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'my_list:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'my_list:tag-list' %}">Tags</a></li>
</ul>

templates/my_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'my_list:tag-list' %}" class="btn btn-primary">Back</a>
  </form>
{% endblock %}

templates/my_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/my_list/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tag List
    <a href="{% url 'my_list:tag-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'my_list:tag-update' pk=tag.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'my_list:tag-delete' pk=tag.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags in the service.</p>
  {% endif %}
{% endblock %}

templates/my_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'my_list:task-list' %}" class="btn btn-primary">Back</a>
  </form>
{% endblock %}

templates/my_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/my_list/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Task list
    <a href="{% url 'my_list:task-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if task_list %}
    <ul class="list-group">
      {% for task in task_list %}
        <li class="list-group-item">
          Content: {{ task.content }}
          <text style="color: red">{% if task.is_done %} Done {% else %} Not done {% endif %}</text>
          <br>
          Created: {{ task.date_time }}<br>
          {% if task.deadline %}Deadline: {{ task.deadline }}{% endif %}
          Tags: {% for tag in task.tags.all %} {{ tag.name }},{% endfor %}
          <a href="{% url 'my_list:task-update' pk=task.pk %}" class="btn btn-primary">Update</a>
          <a href="{% url 'my_list:task-delete' pk=task.pk %}" class="btn btn-danger">Delete</a>
          {% if task.is_done %}
            <form action="{% url 'my_list:toggle-is-done' pk=task.pk %}">
              {% csrf_token %}
              <button formmethod="post" class="btn btn-secondary link-to-page">Undo</button>
            </form>
          {% elif  not task.is_done %}
            <form action="{% url 'my_list:toggle-is-done' pk=task.pk %}">
              {% csrf_token %}
              <button formmethod="post" class="btn btn-success link-to-page">Complete</button>
            </form>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks</p>
  {% endif %}
{% endblock %}